# Generated by Django 5.2.6 on 2025-09-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abrollbehaelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Anhaenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=80)),
                ('kennzeichen', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Brandausbreitung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Brandgut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Brandobjekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Brandumfang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Einsatzmittel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Einsatzstichwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40)),
                ('bezeichnung', models.CharField(max_length=120)),
                ('aktiv', models.BooleanField(default=True)),
                ('kategorie', models.CharField(choices=[('brand', 'Brand'), ('thl', 'Technische Hilfeleistung'), ('sonstig', 'Sonstige')], default='sonstig', max_length=16)),
            ],
            options={
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Fahrzeug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=80)),
                ('funkrufname', models.CharField(max_length=80)),
                ('kennzeichen', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['funkrufname', 'typ'],
            },
        ),
        migrations.CreateModel(
            name='Fehlalarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Loeschwasserentnahmestelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MailEmpfaenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aktiv', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeldendeStelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Mitglied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('vorname', models.CharField(max_length=80)),
                ('agt', models.BooleanField(default=False, verbose_name='Atemschutzgeräteträger')),
                ('hauptamtlich', models.BooleanField(default=False)),
                ('kommandant', models.BooleanField(default=False)),
                ('stv_kommandant', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name', 'vorname'],
            },
        ),
        migrations.CreateModel(
            name='Ortsfeuerwehr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PersonenrettungTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Schadensereignis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Sicherheitswache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Sonstige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Zusatzstelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=120)),
            ],
        ),
    ]
