# Generated by Django 5.2.6 on 2025-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einsatzstichwort',
            name='kategorie',
            field=models.CharField(choices=[('brand', 'Brand'), ('thl', 'Technische Hilfeleistung'), ('abc', 'ABC-Einsatz'), ('info', 'Infoeinsatz'), ('sonstig', 'Sonstige')], default='sonstig', max_length=16),
        ),
    ]
