# Generated by Django 5.2.6 on 2025-09-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_einsatzstichwort_kategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitglied',
            name='jugendfeuerwehr',
            field=models.BooleanField(default=False, verbose_name='Jugendfeuerwehr'),
        ),
    ]
