# Generated by Django 5.2.6 on 2025-09-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dienst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(editable=False)),
                ('seq', models.PositiveIntegerField(editable=False)),
                ('titel', models.CharField(max_length=160)),
                ('start_dt', models.DateTimeField()),
                ('ende_dt', models.DateTimeField()),
                ('beschreibung', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year', '-seq'],
            },
        ),
        migrations.CreateModel(
            name='DienstAbrollbehaelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erforderlich', models.BooleanField(default=False)),
                ('abrollbehaelter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.abrollbehaelter')),
                ('dienst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dienst.dienst')),
            ],
            options={
                'unique_together': {('dienst', 'abrollbehaelter')},
            },
        ),
        migrations.AddField(
            model_name='dienst',
            name='abrollbehaelter',
            field=models.ManyToManyField(blank=True, through='dienst.DienstAbrollbehaelter', to='core.abrollbehaelter'),
        ),
        migrations.CreateModel(
            name='DienstAnhaenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometer', models.PositiveIntegerField(blank=True, null=True)),
                ('stunden', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('anhaenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.anhaenger')),
                ('dienst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dienst.dienst')),
            ],
            options={
                'unique_together': {('dienst', 'anhaenger')},
            },
        ),
        migrations.AddField(
            model_name='dienst',
            name='anhaenger',
            field=models.ManyToManyField(blank=True, through='dienst.DienstAnhaenger', to='core.anhaenger'),
        ),
        migrations.CreateModel(
            name='DienstFahrzeug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometer', models.PositiveIntegerField(blank=True, null=True)),
                ('stunden', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dienst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dienst.dienst')),
                ('fahrzeug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fahrzeug')),
            ],
            options={
                'unique_together': {('dienst', 'fahrzeug')},
            },
        ),
        migrations.AddField(
            model_name='dienst',
            name='fahrzeuge',
            field=models.ManyToManyField(blank=True, through='dienst.DienstFahrzeug', to='core.fahrzeug'),
        ),
        migrations.CreateModel(
            name='DienstTeilnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fahrzeug_funktion', models.CharField(blank=True, max_length=80)),
                ('agt_minuten', models.PositiveIntegerField(blank=True, null=True)),
                ('dienst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dienst.dienst')),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mitglied')),
            ],
            options={
                'unique_together': {('dienst', 'mitglied')},
            },
        ),
        migrations.AddField(
            model_name='dienst',
            name='teilnahmen',
            field=models.ManyToManyField(blank=True, related_name='dienst_teilnahmen', through='dienst.DienstTeilnahme', to='core.mitglied'),
        ),
        migrations.AddConstraint(
            model_name='dienst',
            constraint=models.UniqueConstraint(fields=('year', 'seq'), name='unique_dienst_year_seq'),
        ),
    ]
