# Generated by Django 5.2.6 on 2025-09-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dienst', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dienstteilnahme',
            options={'ordering': ['mitglied__name', 'mitglied__vorname']},
        ),
    ]
