# Generated by Django 5.2.6 on 2025-09-26 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Einsatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(editable=False)),
                ('seq', models.PositiveIntegerField(editable=False)),
                ('start_dt', models.DateTimeField()),
                ('ende_dt', models.DateTimeField()),
                ('einsatzleiter_text', models.CharField(blank=True, max_length=120)),
                ('objektname', models.CharField(blank=True, max_length=120)),
                ('strasse_hausnr', models.CharField(blank=True, max_length=120)),
                ('plz_ort', models.CharField(blank=True, max_length=120)),
                ('einsatzgemeinde', models.CharField(blank=True, max_length=120)),
                ('landkreis', models.CharField(default='Mühldorf am Inn', max_length=120)),
                ('personenrettung_anzahl', models.PositiveIntegerField(blank=True, null=True)),
                ('einsatzmassnahmen', models.TextField(blank=True, verbose_name='Einsatzmaßnahmen / Verwendetes Material')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brandausbreitung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brandausbreitung')),
                ('brandgut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brandgut')),
                ('brandobjekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brandobjekt')),
                ('brandumfang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brandumfang')),
                ('einsatzleiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mitglied')),
                ('fehlalarm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fehlalarm')),
                ('meldende_stelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.meldendestelle')),
                ('personenrettung_typ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.personenrettungtyp')),
                ('schadensereignis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schadensereignis')),
                ('sicherheitswache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sicherheitswache')),
                ('sonstige', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sonstige')),
                ('stichwort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.einsatzstichwort')),
            ],
            options={
                'ordering': ['-year', '-seq'],
            },
        ),
        migrations.CreateModel(
            name='EinsatzAbrollbehaelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erforderlich', models.BooleanField(default=False)),
                ('abrollbehaelter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.abrollbehaelter')),
                ('einsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einsatz.einsatz')),
            ],
            options={
                'unique_together': {('einsatz', 'abrollbehaelter')},
            },
        ),
        migrations.AddField(
            model_name='einsatz',
            name='abrollbehaelter',
            field=models.ManyToManyField(blank=True, through='einsatz.EinsatzAbrollbehaelter', to='core.abrollbehaelter'),
        ),
        migrations.CreateModel(
            name='EinsatzAnhaenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometer', models.PositiveIntegerField(blank=True, null=True)),
                ('stunden', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('erforderlich', models.BooleanField(default=False)),
                ('anhaenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.anhaenger')),
                ('einsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einsatz.einsatz')),
            ],
            options={
                'unique_together': {('einsatz', 'anhaenger')},
            },
        ),
        migrations.AddField(
            model_name='einsatz',
            name='anhaenger',
            field=models.ManyToManyField(blank=True, through='einsatz.EinsatzAnhaenger', to='core.anhaenger'),
        ),
        migrations.CreateModel(
            name='EinsatzEinsatzmittel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.PositiveIntegerField()),
                ('einsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einsatz.einsatz')),
                ('einsatzmittel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.einsatzmittel')),
            ],
            options={
                'unique_together': {('einsatz', 'einsatzmittel')},
            },
        ),
        migrations.AddField(
            model_name='einsatz',
            name='einsatzmittel',
            field=models.ManyToManyField(blank=True, through='einsatz.EinsatzEinsatzmittel', to='core.einsatzmittel'),
        ),
        migrations.CreateModel(
            name='EinsatzFahrzeug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometer', models.PositiveIntegerField(blank=True, null=True)),
                ('stunden', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('erforderlich', models.BooleanField(default=False)),
                ('einsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einsatz.einsatz')),
                ('fahrzeug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fahrzeug')),
            ],
            options={
                'unique_together': {('einsatz', 'fahrzeug')},
            },
        ),
        migrations.AddField(
            model_name='einsatz',
            name='fahrzeuge',
            field=models.ManyToManyField(blank=True, through='einsatz.EinsatzFahrzeug', to='core.fahrzeug'),
        ),
        migrations.CreateModel(
            name='EinsatzLoeschwasser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menge', models.DecimalField(blank=True, decimal_places=2, help_text='z. B. m³', max_digits=7, null=True)),
                ('einsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loeschwasser', to='einsatz.einsatz')),
                ('entnahmestelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.loeschwasserentnahmestelle')),
            ],
        ),
        migrations.CreateModel(
            name='EinsatzOrtsfeuerwehr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erforderlich', models.BooleanField(default=False)),
                ('einsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einsatz.einsatz')),
                ('ortsfeuerwehr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ortsfeuerwehr')),
            ],
            options={
                'unique_together': {('einsatz', 'ortsfeuerwehr')},
            },
        ),
        migrations.AddField(
            model_name='einsatz',
            name='ortsfeuerwehren',
            field=models.ManyToManyField(blank=True, through='einsatz.EinsatzOrtsfeuerwehr', to='core.ortsfeuerwehr'),
        ),
        migrations.CreateModel(
            name='EinsatzPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('geschaedigter', 'Geschädigter'), ('kostentraeger', 'Kostenträger'), ('eigentuerer', 'Eigentümer'), ('verursacher', 'Verursacher')], max_length=20)),
                ('name_vorname', models.CharField(max_length=120)),
                ('strasse_hausnr', models.CharField(blank=True, max_length=120)),
                ('plz_ort', models.CharField(blank=True, max_length=120)),
                ('telefon', models.CharField(blank=True, max_length=60)),
                ('kfz_kennz', models.CharField(blank=True, max_length=30)),
                ('kostenbefreit', models.BooleanField(default=False)),
                ('begruendung', models.CharField(blank=True, max_length=180)),
                ('einsatz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='einsatz.einsatz')),
            ],
        ),
        migrations.CreateModel(
            name='EinsatzTeilnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fahrzeug_funktion', models.CharField(blank=True, max_length=80)),
                ('agt_minuten', models.PositiveIntegerField(blank=True, null=True)),
                ('einsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einsatz.einsatz')),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mitglied')),
            ],
            options={
                'unique_together': {('einsatz', 'mitglied')},
            },
        ),
        migrations.AddField(
            model_name='einsatz',
            name='teilnahmen',
            field=models.ManyToManyField(blank=True, related_name='einsatz_teilnahmen', through='einsatz.EinsatzTeilnahme', to='core.mitglied'),
        ),
        migrations.CreateModel(
            name='EinsatzZusatzstelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('einsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einsatz.einsatz')),
                ('zusatzstelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.zusatzstelle')),
            ],
            options={
                'unique_together': {('einsatz', 'zusatzstelle')},
            },
        ),
        migrations.AddField(
            model_name='einsatz',
            name='zusatzstellen',
            field=models.ManyToManyField(blank=True, through='einsatz.EinsatzZusatzstelle', to='core.zusatzstelle'),
        ),
        migrations.AddConstraint(
            model_name='einsatz',
            constraint=models.UniqueConstraint(fields=('year', 'seq'), name='unique_einsatz_year_seq'),
        ),
    ]
